org: rishavai
service: smart-portfolio-api

provider:
  name: aws
  runtime: python3.11
  region: eu-central-1
  timeout: 29
  memorySize: 1024                 # more CPU
  stage: dev
  environment:
    GOOGLE_API_KEY: ${env:GOOGLE_API_KEY}
    FINNHUB_API_KEY: ${env:FINNHUB_API_KEY}     # << add this for Finnhub
    ALLOW_FRACTIONAL_SHARES: "true"
    ALLOWED_ORIGINS: "http://localhost:5173,https://smart-portfolio-generator-iota.vercel.app"

functions:
  app:
    handler: main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: true
    useStaticCache: false
    useDownloadCache: false

package:
  patterns:
    - data/**                 # include your tickers file(s)
    - '!frontend/**'
    - '!venv/**'
    - '!.venv/**'
    - '!node_modules/**'
    - '!**/__pycache__/**'
    - '!.serverless/**'
    - '!*.zip'
    - '!.env'
