org: rishavai
service: smart-portfolio-api

provider:
  name: aws
  runtime: python3.11
  region: eu-central-1
  timeout: 29
  memorySize: 512
  stage: dev

functions:
  app:
    handler: main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: true
    useStaticCache: false
    useDownloadCache: false
    noDeploy:
      - pip
      - setuptools
      - wheel

package:
  individually: true
  exclude:
    - venv/**
    - .venv/**
    - node_modules/**
    - __pycache__/**
    - .pytest_cache/**
    - .serverless/**
    - .DS_Store
    - '*.zip'
    - frontend/**
    - .env
